language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  fast_finish: true

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

script:
  - make setup
  - find . -type f -name "*.php" | grep -v vendor | xargs -n 1 php -l
  - make test
  - make check-style
